---
# Default settings for all files
CompileFlags:
  Add:
    - -Wall
    - -Wextra
    - -I/usr/include/c++/11
    - -I/usr/include/x86_64-linux-gnu/c++/11
    - -I/usr/include/x86_64-linux-gnu
    - -I/usr/include

---
# Settings specifically for C files
If:
  PathMatch: .*\.c$

CompileFlags:
  Remove: 
    - -std=c++*
  Add:
    - -std=c17

---
# Settings specifically for C++ files
If:
  PathMatch: .*\.(cpp|cc|cxx|hpp|hxx|h)$

CompileFlags:
  Add:
    - -std=c++17
